### ISSUE TITLE
Fix NoSuchFileException in alto convert Taskmanager Plugin

### ISSUE THREAD

**Issue by H-Bluhm** [wellcometrust/workflow#161]
<code>
error copying from S3: 
java.nio.file.NoSuchFileException: /ebs/e2c48201-170f-43b3-9340-74a55333fec8/efs/digiverso/goobi/metadata/275590/images/source/b30094392_jp2/b30094392_0000.jp2 
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) 
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) 
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) 
at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) 
at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) 
at java.nio.file.Files.newOutputStream(Files.java:216) at java.nio.file.Files.copy(Files.java:3016) 
at de.intranda.digiverso.ocr.control.S3Helper.downloadS3ObjectToFolder(S3Helper.java:119) 
at de.intranda.digiverso.ocr.control.S3Helper.downloadPrefixToDir(S3Helper.java:65) 
at de.intranda.digiverso.ocr.control.GenerateAltoFiles.main(GenerateAltoFiles.java:103) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:498) 
at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
</code>

**Comment by H-Bluhm** [comment]
Plugin did not account for sub prefixes to be downloaded, leading to an attempt to write a file to a nonexistent directory.
