### ISSUE TITLE
bagit creation: not able to work on CIFS

### ISSUE THREAD

**Issue by mgeerdsen** [wellcometrust/workflow#191]
CIFS behaviour is preventing usage of CIFS as temporary storage currently:

`ERROR 2019-08-21 13:36:57.052 [main] de.intranda.wellcome_export_bagit.Bagit_loc.setMetadata(Bagit_loc.java:664)
    Unable to create bag
java.nio.file.AccessDeniedException: /opt/digiverso/shellserver/tampa/tmp-working-storage/193f730a-44aa-472c-96d0-ef918bf37734/b30510478/objects -> /opt/digiverso/shellserver/tampa/tmp-working-storage/193f730a-44aa-472c-96d0-ef918bf37734/b30510478/1566391017031.temp/objects
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:1.8.0_222]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_222]
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:457) ~[?:1.8.0_222]
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262) ~[?:1.8.0_222]
        at java.nio.file.Files.move(Files.java:1395) ~[?:1.8.0_222]
        at gov.loc.repository.bagit.creator.BagCreator.moveDataFiles(BagCreator.java:159) ~[wellcome-export-bagit.jar:?]
        at gov.loc.repository.bagit.creator.BagCreator.moveDataFilesIfNeeded(BagCreator.java:142) ~[wellcome-export-bagit.jar:?]
        at gov.loc.repository.bagit.creator.BagCreator.bagInPlace(BagCreator.java:125) ~[wellcome-export-bagit.jar:?]
        at gov.loc.repository.bagit.creator.BagCreator.bagInPlace(BagCreator.java:78) ~[wellcome-export-bagit.jar:?]
        at de.intranda.wellcome_export_bagit.Bagit_loc.setMetadata(Bagit_loc.java:659) [wellcome-export-bagit.jar:?]
        at de.intranda.wellcome_export_bagit.Bagit_loc.run(Bagit_loc.java:198) [wellcome-export-bagit.jar:?]
        at de.intranda.wellcome_export_bagit.Bagit_loc.main(Bagit_loc.java:123) [wellcome-export-bagit.jar:?]`

Probably an unclosed file which is tried to be moved.

**Comment by opaetzel** [comment]
workaround is a larger storage on salzburg and not relevant for AWS
